# Generated by Django 2.2.4 on 2021-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(db_column='cityName', max_length=255)),
                ('citynameeng', models.CharField(db_column='cityNameEng', max_length=255)),
                ('datatime', models.DateTimeField(db_column='dataTime')),
                ('so2value', models.CharField(db_column='so2Value', max_length=10)),
                ('covalue', models.CharField(db_column='coValue', max_length=10)),
                ('o3value', models.CharField(db_column='o3Value', max_length=10)),
                ('no2value', models.CharField(db_column='no2Value', max_length=10)),
                ('pm10value', models.CharField(db_column='pm10Value', max_length=10)),
                ('pm25value', models.CharField(db_column='pm25Value', max_length=10)),
            ],
            options={
                'db_table': 'air',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corona19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdt', models.DateTimeField()),
                ('statedt', models.DateField()),
                ('statetime', models.TimeField()),
                ('decidecnt', models.CharField(max_length=255)),
                ('carecnt', models.CharField(max_length=255)),
                ('clearcnt', models.CharField(max_length=255)),
                ('deathcnt', models.CharField(max_length=255)),
                ('examcnt', models.CharField(db_column='examCnt', max_length=255)),
                ('resutlnegcnt', models.CharField(max_length=255)),
                ('accdefrate', models.CharField(max_length=255)),
                ('accexamcnt', models.CharField(db_column='accExamCnt', max_length=255)),
                ('accexamcompcnt', models.CharField(db_column='accExamCompCnt', max_length=255)),
            ],
            options={
                'db_table': 'corona19',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('urltoimage', models.CharField(blank=True, db_column='urlToImage', max_length=256, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basedate', models.DateField(db_column='baseDate')),
                ('basetime', models.TimeField(db_column='baseTime')),
                ('category', models.CharField(max_length=4)),
                ('fcstdate', models.DateField(db_column='fcstDate')),
                ('fcsttime', models.TimeField(db_column='fcstTime')),
                ('fcstvalue', models.CharField(blank=True, db_column='fcstValue', max_length=5, null=True)),
                ('nx', models.IntegerField()),
                ('ny', models.IntegerField()),
            ],
            options={
                'db_table': 'weather',
                'managed': False,
            },
        ),
    ]
